DROP TABLE IF EXISTS history_2500_0;
CREATE TABLE history_2500_0 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_0.csv';

DROP TABLE IF EXISTS history_2500_230;
CREATE TABLE history_2500_230 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_230.csv';

DROP TABLE IF EXISTS history_2500_460;
CREATE TABLE history_2500_460 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_460.csv';

DROP TABLE IF EXISTS history_2500_690;
CREATE TABLE history_2500_690 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_690.csv';

DROP TABLE IF EXISTS history_2500_920;
CREATE TABLE history_2500_920 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_920.csv';

DROP TABLE IF EXISTS history_2500_1150;
CREATE TABLE history_2500_1150 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_1150.csv';

DROP TABLE IF EXISTS history_2500_1380;
CREATE TABLE history_2500_1380 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_1380.csv';

DROP TABLE IF EXISTS history_2500_1610;
CREATE TABLE history_2500_1610 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_1610.csv';

DROP TABLE IF EXISTS history_2500_1840;
CREATE TABLE history_2500_1840 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_1840.csv';

DROP TABLE IF EXISTS history_2500_2070;
CREATE TABLE history_2500_2070 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_2070.csv';

DROP TABLE IF EXISTS history_2500_2298;
CREATE TABLE history_2500_2298 (
    time bigint PRIMARY KEY,
ES_H double precision, 
ES_L double precision, 
ES_C double precision, 
NQ_H double precision, 
NQ_L double precision, 
NQ_C double precision, 
VIX_H double precision, 
VIX_L double precision, 
VIX_C double precision, 
VX_H double precision, 
VX_L double precision, 
VX_C double precision, 
US_H double precision, 
US_L double precision, 
US_C double precision, 
GC_H double precision, 
GC_L double precision, 
GC_C double precision, 
CL_H double precision, 
CL_L double precision, 
CL_C double precision, 
EC_H double precision, 
EC_L double precision, 
EC_C double precision, 
S_H double precision, 
S_L double precision, 
S_C double precision, 
W_H double precision, 
W_L double precision, 
W_C double precision
);

\copy history from 'history_2500_2298.csv';

